#+startup:fold
#+BABEL: :session *python* :cache yes :results output graphics :exports both :tangle yes 
* ------------------------------------------------------------------------------
* directory: file:./
* figures  : file:figures/
* ------------------------------------------------------------------------------
* note: file:tmp/mu2e-50071.pdf
* setup                                                                      
#+begin_src
git clone https://github.com/pavel1murat/mu2e-50071.degrader_rpc
bibdir=<bib_dir> # choose the name
git clone https://github.com/pavel1murat/mu2e_bibliography  bibdir
export BIBINPUTS=$PWD/bibdir
cd mu2e-50071.degrader_rpc
make note
okular tpm/mu2e-50071.pdf &
#+end_src
* figures in the note                                                         
- all figures made by scripts, see : file:scripts/plot.C 
* digitized figures from Bistirlich et al (1971) : file:csv
* degrader geometry and weight                                               
 4mm TI: 0.4*4.5 = 1.8g/cm^2
 9mm CH2 + 1.0mm Pb: : 2.0 g/cm^2   .. \pi*15^2*(0.9*0.95 + 0.08*11.34): approx 2 g/cm^2
 9mm CH2 + 0.8mm Pb: : 1.76 g/cm^2 

- reduce the outer radius: don't need R=15cm

 CH2 disk R=14 cm, weight        : 0.9*0.95*\pi*14^2 = 526 gr
 Pb  foil R=10cm thickness 0.8mm : 0.08*11.34*314    = 285 gr
 total                           : 811 gr
 
* absolute rates:                                                            
- use histogram files : pipenu.bpim0b0s24r0000.murat_spmc_ana.0000.hist
| ! |             | hist           | sw_ch2 |  fr_ch2 |  sw_pb |   fr_pb | sw_tgt |  fr_tgt |
| $ | npot=2.5e8  |                |        |         |        |         |        |         |
|---+-------------+----------------+--------+---------+--------+---------+--------+---------|
| # | total stops |                |   1260 | 5.0e-06 |  792.3 | 3.2e-06 |  243.2 | 9.7e-07 |
| # | T>150 ns    | simp_215/etime |  657.7 | 2.6e-06 |  4.766 | 1.9e-08 |  28.09 | 1.1e-07 |
| # | T>200 ns    | simp_215/etime |  67.42 | 2.7e-07 | 0.0141 | 5.6e-11 | 0.0914 | 3.7e-10 |
|---+-------------+----------------+--------+---------+--------+---------+--------+---------|
#+TBLFM: $5=$sw_ch2/$npot;%8.1e::$7=$sw_pb/$npot;%8.1e::$9=$sw_tgt/$npot;%8.1e::

with the new degrader geometry: R=250 mm  100 um thick :

139 events in the histogram per 10^5 events generated with 0 < cos(theta) < 0.1.
This corresponds to the acceptance of 139/10^5*0.1/2 = 1.4e-3*5e-2 = 7e-5

estimate of the probability to reconstruct an event:

          7e-5(prob_of_a_photon_conversion_event)*1.e-2(H2_fraction)*0.4(BR pi-p --> n gamma) = 2.8.e-7

per POT: 2.7-7(prob_to_stop)*2.8e-7 = 7.5e-14;

- 1-batch mode: 1.6e7 POT/pulse x 1.6e5 pulses/sec = 2.5e12 protons/sec
- assume 10% intensity and 50% data taking efficiency: f = 0.05 = 5.e-2
- under these assumptions: ~ 1.2e11 protons/sec
- 1 day: 86400 sec ==> 1.1e16 POT times 7.5e-14 = 800 events

- 2-batch mode, same assumptions: 
  3.9e7 POT/pulse x 1.6e5 pulses/sec = 6.2e12 protons/sec x 5.e-2 (eff) x 86400 = 2.7e16 POT / day

- under the same assumptions, for 2-batch mode: x2.5 .... 2,000 events

so reducing intensity by an additional factor and starting from an earlier time
could be beneficial

* fit RPC yield on CH2                                                       
- code: file:scripts/fit_ch2.C
- preliminary results: file:./figures/png/fit_preliminary.png
- the outcome: (1-fH2)*0.75  
* energy loss correlation with the photon emission angle                     
  file:figures/png/rpc03b0s44r0000_drpc_2_smvd13_vs_sinth.png
* Jim Miller: assumptions                                                    

- There are about 2000 times (?) fewer stopped pions compared to muons in the target.
  > the total fraction is about 1/300, but the number itself doesn't mean much:
      the timing cut makes a huge difference
      
- The target has a thickness of 37 plates x 0.01 cm thickness x 2.7 g/cm3 density =0.999 g/cm2
  > OK
  
- The rate of stopped muons at full intensity is 1e10 per second in the Stopping Target.
  > 3.9e7*1.6e-3*1.6e5 \sim 1e10/sec

- The rate of stopped pions in the poly is therefore estimated at 1e10/2000=5e6/s (?)
  > the same comment about the timing cut
  
- 3% of pions stop on hydrogen and 1/3 (?) produce a 129.4 MeV gamma. .03/3*5e6=5e4/s
  > fraction of stopped puons in the peak: 1% \times 0.4 = 4e-3

- Fractional solid angle of gold foil is approximately (pretend it is part of a sphere) =
  3 cm wide x 2pi x 25 cm radius)/(4pi *25**2)=0.06
  > can't make 3cm wide foil, ~1cm max...

- So we get .06*5e4=3e3/s 129 MeV gammas incident on the gold and producing pairs

- Maybe 10% (a guess) have roughly equal e+ and e- energies, so 3e2 viable pairs per second.
  > this rate is known: for the simulated geometry, and 100 um thickness, the rate of events
  > of interest is ~140e-5/20 = 7.e-5,
  > acceptance: 1cm*2pi*25/4pi/25/25 = 1/50 = 2e-2
  > thickness:  100um/3.3mm ~ 0.03 Xrad, the product is 6e-4
  > out of that, about 10% are evens with two particles 20 hits each , above 30 MeV/c
  
- Maybe 1/3 will go downstream with a high enough helical dip angle, 100/s

- We have to turn the beam down by x10 so the detectors can handle the flash, 10/s
* RPC on hydrogen: the photon energy                                         
 - pi- p -- > n gamma, stopped pi^-
#             .. #+begin_src python :var fn = "a.png" :session :results none 
# turns out that :session prevents the graphics window from opening
# replace 'none' with 'file' for writing output into a file
#+begin_src python :session :var mp=938.272 :var mn=939.565 :var mpi=139.57
  pgamma = ((mp+mpi)*(mp+mpi)-mn*mn)/2/(mp+mpi);
  output = "pgamma = %10.3f"%pgamma
  (output)
#+end_src

#+RESULTS:
: pgamma =    129.407

* ------------------------------------------------------------------------------
